name: groot
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - lightning=2.2.1
  - pip=24.0
  - python=3.10.14
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  - pip:
      - transformers==4.42.0
      - networkx==3.3
      - torch_geometric==2.5.2
      - scikit-learn==1.4.1.post1
      - matplotlib==3.8.4
      - pandas==2.2.1
      - seaborn==0.13.2
      - omegaconf==2.3.0
      - wandb==0.16.6
      - polyleven==0.8
      - rich